export const taskData = [
  {
    id: 1,
    title: "Attend Jay’s School Event",
    time: "06:00 PM - 08:00 PM",
    location: "Samson Street",
    description: "Lorem ipsum dolor sit amet consectetur.",
    completed: false,
  },
  {
    id: 2,
    title: "Talk to the lawyer about case",
    time: "06:00 PM - 08:00 PM",
    location: "Samson Street",
    description: "Lorem ipsum dolor sit amet consectetur.",
    completed: false,
  },
  {
    id: 3,
    title: "Clear the laundry",
    time: "06:00 PM - 08:00 PM",
    location: "Samson Street",
    description: "Lorem ipsum dolor sit amet consectetur.",
    completed: false,
  },
  {
    id: 4,
    title: "Upload the pending documents",
    time: "06:00 PM - 08:00 PM",
    location: "Samson Street",
    description: "Lorem ipsum dolor sit amet consectetur.",
    completed: false,
  },
  {
    id: 5,
    title: "Attend Jay’s School Event",
    time: "06:00 PM - 08:00 PM",
    location: "Samson Street",
    description: "Lorem ipsum dolor sit amet consectetur.",
    completed: true,
  },
  {
    id: 6,
    title: "Talk to the lawyer about case",
    time: "06:00 PM - 08:00 PM",
    location: "Samson Street",
    description: "Lorem ipsum dolor sit amet consectetur.",
    completed: true,
  },
];
